version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ./angular-front/Dockerfile
    image: my-app-nginx
    ports:
      - "80:80"
    depends_on:
      - nestjs

  nestjs:
    build:
      context: ./nestjs-server
      dockerfile: Dockerfile
    image: my-app-nest
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
